const products = [
  {
    name: "Esponja 3D Dazzle",
    infoAdd: undefined,
    price: "36,90",
    promotion: "29,90",
    category: "more sales",
    img: "../assets/img-cards/esponja.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Base Líquida Hyaluronic Hydra Dazzle ",
    infoAdd: "Escuro 2 - 500g",
    price: "89,90",
    promotion: undefined,
    category: "more sales",
    img: "../assets/img-cards/base-líquida.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Grace La Rose Sublime Deo Colônia Pocket 15ml",
    price: "39,90",
    infoAdd: "15ml",
    promotion: undefined,
    category: "more sales",
    img: "../assets/img-cards/grace-la-rose.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Pó Compacto HD Cover ",
    price: "46,90",
    infoAdd: "Claro 2 Dazzle - 12g",
    promotion: undefined,
    category: "more sales",
    img: "../assets/img-cards/po-compacto.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Gel Modelador 500g",
    price: "60,00",
    infoAdd: "500g",
    promotion: undefined,
    category: "most desired",
    img: "../assets/img-cards/corps.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Shake de Vanilla H+ HND",
    price: "99,90",
    infoAdd: "550g",
    promotion: "79,90",
    category: "most desired",
    img: "../assets/img-cards/shake-vanilha.svg",
    discount: "-20",
    portion: 2,
  },
  {
    name: "Shake de Morango H+ HND - 550g",
    price: "99,90",
    infoAdd: "550g",
    promotion: "79,90",
    category: "most desired",
    img: "../assets/img-cards/shake-morango.svg",
    discount: "-20",
    portion: 2,
  },
  {
    name: "Luva de Silicone Creme para as Mãos Hands",
    price: "25,90",
    infoAdd: "100g",
    promotion: "29,90",
    category: "most desired",
    img: "../assets/img-cards/luva-silicone.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Café Verde ",
    price: "69,90",
    infoAdd: "120 cápsulas",
    promotion: undefined,
    category: "healthy life",
    img: "../assets/img-cards/cafe-verde.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Ácido Hialurônico com Colágeno HND",
    price: "175,00",
    infoAdd: " 30 Sachês de 4g",
    promotion: undefined,
    category: "healthy life",
    img: "../assets/img-cards/acido.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Slim Max HND ",
    price: "140,00",
    infoAdd: "120 Cápsulas",
    promotion: undefined,
    category: "healthy life",
    img: "../assets/img-cards/slim.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Chá H+ Frutas Vermelhas ",
    price: "45,00",
    infoAdd: " 150g",
    promotion: undefined,
    category: "healthy life",
    img: "../assets/img-cards/cha-h.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Wonderful Gold Óleo para as  ",
    price: "45,00",
    infoAdd: "Pernas - 150ml",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/oleo-pernas.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Esfoliante ",
    price: "49,00",
    infoAdd: "Corporal - 200g",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/esfoliante2.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Gel para Massagem Feelin Hot Morango ",
    price: "27,00",
    infoAdd: "60ml",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/gel-hot.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Óleo para as Pernas Wonderful ",
    price: "39,90",
    infoAdd: "140ml",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/oleo-pernas140ml.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Gel Modelador",
    price: "60,00",
    infoAdd: "500g",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/gel1.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Gel Modelador ",
    price: "60,00",
    infoAdd: "500g",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/gel2.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Gel Modelador ",
    price: "60,00",
    infoAdd: "500g",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/gel3.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Corps Lígnea Body Contour Gel Modelador ",
    price: "60,00",
    infoAdd: "500g",
    promotion: undefined,
    category: "body and bath",
    img: "../assets/img-cards/gel4.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Lattitude Expedition ",
    price: "129,00",
    infoAdd: "100ML",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/lattitude-exp.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Empire VIP ",
    price: "150,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/empire-vip.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Empire ",
    price: "150,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/empire.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Lattitude Stamina ",
    price: "129,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/lattitude-stamina.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Empire Gold ",
    price: "150,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/empire-gold.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Colônia Lattitude Origini ",
    price: "129,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/lattitude-col.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Colônia Ella Juicy ",
    price: "129,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/ella.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Spot For Her ",
    price: "129,00",
    infoAdd: "75ml",
    promotion: undefined,
    category: "fragrances",
    img: "../assets/img-cards/spot.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Deo Colônia Venyx L'Or ",
    price: "150,00",
    infoAdd: "100ml",
    promotion: undefined,
    category: "new",
    img: "../assets/img-cards/deo.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Desodorante Roll On Dynamic",
    price: "17,90",
    infoAdd: undefined,
    promotion: undefined,
    category: "new",
    img: "../assets/img-cards/deso.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "Erva Doce Sabonete Cremoso Facial Hinode ",
    price: "33,40",
    infoAdd: "250ml",
    promotion: undefined,
    category: "new",
    img: "../assets/img-cards/erva.svg",
    discount: undefined,
    portion: 2,
  },
  {
    name: "HND Shake Triple Chocolate",
    price: "109,90",
    infoAdd: " 450g",
    promotion: undefined,
    category: "new",
    img: "../assets/img-cards/hnd.svg",
    discount: undefined,
    portion: 2,
  },
];

export default products;
